name: VibeRemote
options:
  bundleIdPrefix: com.vibeRemote
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.2.0
  Citadel:
    url: https://github.com/orlandos-nl/Citadel.git
    from: 0.7.0

targets:
  VibeRemote:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: SwiftTerm
      - package: Citadel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vibeRemote.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
